language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
install:
  - npm install -g codecov
script:
  - npm run lint
  - npm run build
  - npm test
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      codecov && npm run deploy-storybook;
    fi
